### ISSUE TITLE
linking error while making

### ISSUE THREAD

**Issue by mrmartin** [kyamagu/matlab-leveldb#3]
There is an error with the linking command:
```
-> g++ -O -fPIC -pthread -shared -Wl,--version-script,/usr/local/MATLAB/extern/lib/glnxa64/mexFunction.map -Wl,--no-undefined -o  "+leveldb/private/LevelDB_.mexa64"  LevelDB_.o  leveldb-1.18/libleveldb.a -Wl,-rpath-link,/usr/local/MATLAB/bin/glnxa64 -L/usr/local/MATLAB/bin/glnxa64 -lmx -lmex -lmat -lm

/usr/bin/ld: leveldb-1.18/libleveldb.a(db_impl.o): relocation R_X86_64_32S against `_ZTVN7leveldb2DBE' can not be used when making a shared object; recompile with -fPIC
leveldb-1.18/libleveldb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
[...]
```

I tried -std=gnu++11, -std=c++0x, and -std=c++11 in CXXFLAGS. Before adding -fPIC to LDFLAGS to mexopts.sh, the error was the same.

Does it have anything to do with
```
rm -f libleveldb.a
```
which is done earlier in the make?

**Comment by kyamagu** [comment]
This has to do with missing `-fPIC` in leveldb compilation. I'll look into the detail...

**Comment by kyamagu** [comment]
Can you try out the `dynamic-link` branch?

https://github.com/kyamagu/matlab-leveldb/tree/dynamic-link

There is a way to fix `-fPIC` using the current build procedure, but that could introduce an additional dependency to Snappy library which is a bit troublesome.

**Comment by mrmartin** [comment]
I added -lsnappy to CXXLIBS in mexopts.sh, and adding -fPIC to OPT in the leveldb-1.18/Makefile.
Now it compiles, and it works. Thank you!

After adding -fPIC to leveldb/Makefile, perhaps there is no need to add snappy? Linking could simply be done with
```
sed -i 's/OPT ?= -O2 -DNDEBUG/OPT ?= -fPIC -O2 -DNDEBUG/g' $(LEVELDB_DIR)/Makefile
``` 
in your makefile.

I tried both the main branch and the `dynamic-link` branch, and I had exactly the same problems and results.

**Comment by kyamagu** [comment]
@mrmartin I do not recommend modifying the `mexopts.sh` in the home directory. A better solution for doing that is to copy `mexopts.sh` into the `matlab-leveldb` directory, modify, and compile the code from there. Otherwise you might find a trouble when you build a different MEX file. Anyway, the `dynamic-link` repo should work fine as long as LevelDB is installed to the system.

The necessity for snappy (`-lsnappy`) depends on the availability of the library in the platform. To really compatible with various UNIX platforms, we have to include a platform detection script. But that takes a bit of efforts. Meanwhile I recommend dynamic linking.

**Comment by mrmartin** [comment]
Thank you for those tips. This problem is now solved.
